local Intel8080 = require "intel8080.base"
Intel8080.langdef = {}

Intel8080.langdef.opcodes = {
    [0x00] = {name = "NOP",  args = {}},
    [0x01] = {name = "LXI",  args = {{register_pair = "B"}, {word = "data"}}},
    [0x02] = {name = "STAX", args = {{register_pair = "B"}}},
    [0x03] = {name = "INX",  args = {{register_pair = "B"}}},
    [0x04] = {name = "INR",  args = {{register = "B"}}},
    [0x05] = {name = "DCR",  args = {{register = "B"}}},
    [0x06] = {name = "MVI",  args = {{register = "B"}, {byte = "data"}}},
    [0x07] = {name = "RLC",  args = {}},
    [0x09] = {name = "DAD",  args = {{register_pair = "B"}}},
    [0x0a] = {name = "LDAX", args = {{register_pair = "B"}}},
    [0x0b] = {name = "DCX",  args = {{register_pair = "B"}}},
    [0x0c] = {name = "INR",  args = {{register = "C"}}},
    [0x0d] = {name = "DCR",  args = {{register = "C"}}},
    [0x0e] = {name = "MVI",  args = {{register = "C"}, {byte = "data"}}},
    [0x0f] = {name = "RRC",  args = {}},

    [0x11] = {name = "LXI",  args = {{register_pair = "D"}, {word = "data"}}},
    [0x12] = {name = "STAX", args = {{register_pair = "D"}}},
    [0x13] = {name = "INX",  args = {{register_pair = "D"}}},
    [0x14] = {name = "INR",  args = {{register = "D"}}},
    [0x15] = {name = "DCR",  args = {{register = "D"}}},
    [0x16] = {name = "MVI",  args = {{register = "D"}, {byte = "data"}}},
    [0x17] = {name = "RAL",  args = {}},
    [0x19] = {name = "DAD",  args = {{register_pair = "D"}}},
    [0x1a] = {name = "LDAX", args = {{register_pair = "D"}}},
    [0x1b] = {name = "DCX",  args = {{register_pair = "D"}}},
    [0x1c] = {name = "INR",  args = {{register = "E"}}},
    [0x1d] = {name = "DCR",  args = {{register = "E"}}},
    [0x1e] = {name = "MVI",  args = {{register = "E"}, {byte = "data"}}},
    [0x1f] = {name = "RAR",  args = {}},

    [0x21] = {name = "LXI",  args = {{register_pair = "H"}, {word = "data"}}},
    [0x22] = {name = "SHLD", args = {{word = "address"}}},
    [0x23] = {name = "INX",  args = {{register_pair = "H"}}},
    [0x24] = {name = "INR",  args = {{register = "H"}}},
    [0x25] = {name = "DCR",  args = {{register = "H"}}},
    [0x26] = {name = "MVI",  args = {{register = "H"}, {byte = "data"}}},
    [0x27] = {name = "DAA",  args = {}},
    [0x29] = {name = "DAD",  args = {{register_pair = "H"}}},
    [0x2a] = {name = "LHLD", args = {{word = "address"}}},
    [0x2b] = {name = "DCX",  args = {{register_pair = "H"}}},
    [0x2c] = {name = "INR",  args = {{register = "L"}}},
    [0x2d] = {name = "DCR",  args = {{register = "L"}}},
    [0x2e] = {name = "MVI",  args = {{register = "L"}, {byte = "data"}}},
    [0x2f] = {name = "CMA",  args = {}},

    [0x31] = {name = "LXI",  args = {{register_pair = "SP"}, {word = "data"}}},
    [0x32] = {name = "STA",  args = {{word = "address"}}},
    [0x33] = {name = "INX",  args = {{register_pair = "SP"}}},
    [0x34] = {name = "INR",  args = {{register = "M"}}},
    [0x35] = {name = "DCR",  args = {{register = "M"}}},
    [0x36] = {name = "MVI",  args = {{register = "M"}, {byte = "data"}}},
    [0x37] = {name = "STC",  args = {}},
    [0x39] = {name = "DAD",  args = {{register_pair = "SP"}}},
    [0x3a] = {name = "LDA",  args = {{word = "address"}}},
    [0x3b] = {name = "DCX",  args = {{register_pair = "SP"}}},
    [0x3c] = {name = "INR",  args = {{register = "A"}}},
    [0x3d] = {name = "DCR",  args = {{register = "A"}}},
    [0x3e] = {name = "MVI",  args = {{register = "A"}, {byte = "data"}}},
    [0x3f] = {name = "CMC",  args = {}},

    [0x40] = {name = "MOV",  args = {{register = "B"}, {register = "B"}}},
    [0x41] = {name = "MOV",  args = {{register = "B"}, {register = "C"}}},
    [0x42] = {name = "MOV",  args = {{register = "B"}, {register = "D"}}},
    [0x43] = {name = "MOV",  args = {{register = "B"}, {register = "E"}}},
    [0x44] = {name = "MOV",  args = {{register = "B"}, {register = "H"}}},
    [0x45] = {name = "MOV",  args = {{register = "B"}, {register = "L"}}},
    [0x46] = {name = "MOV",  args = {{register = "B"}, {register = "M"}}},
    [0x47] = {name = "MOV",  args = {{register = "B"}, {register = "A"}}},
    [0x48] = {name = "MOV",  args = {{register = "C"}, {register = "B"}}},
    [0x49] = {name = "MOV",  args = {{register = "C"}, {register = "C"}}},
    [0x4a] = {name = "MOV",  args = {{register = "C"}, {register = "D"}}},
    [0x4b] = {name = "MOV",  args = {{register = "C"}, {register = "E"}}},
    [0x4c] = {name = "MOV",  args = {{register = "C"}, {register = "H"}}},
    [0x4d] = {name = "MOV",  args = {{register = "C"}, {register = "L"}}},
    [0x4e] = {name = "MOV",  args = {{register = "C"}, {register = "M"}}},
    [0x4f] = {name = "MOV",  args = {{register = "C"}, {register = "A"}}},

    [0x50] = {name = "MOV",  args = {{register = "D"}, {register = "B"}}},
    [0x51] = {name = "MOV",  args = {{register = "D"}, {register = "C"}}},
    [0x52] = {name = "MOV",  args = {{register = "D"}, {register = "D"}}},
    [0x53] = {name = "MOV",  args = {{register = "D"}, {register = "E"}}},
    [0x54] = {name = "MOV",  args = {{register = "D"}, {register = "H"}}},
    [0x55] = {name = "MOV",  args = {{register = "D"}, {register = "L"}}},
    [0x56] = {name = "MOV",  args = {{register = "D"}, {register = "M"}}},
    [0x57] = {name = "MOV",  args = {{register = "D"}, {register = "A"}}},
    [0x58] = {name = "MOV",  args = {{register = "E"}, {register = "B"}}},
    [0x59] = {name = "MOV",  args = {{register = "E"}, {register = "C"}}},
    [0x5a] = {name = "MOV",  args = {{register = "E"}, {register = "D"}}},
    [0x5b] = {name = "MOV",  args = {{register = "E"}, {register = "E"}}},
    [0x5c] = {name = "MOV",  args = {{register = "E"}, {register = "H"}}},
    [0x5d] = {name = "MOV",  args = {{register = "E"}, {register = "L"}}},
    [0x5e] = {name = "MOV",  args = {{register = "E"}, {register = "M"}}},
    [0x5f] = {name = "MOV",  args = {{register = "E"}, {register = "A"}}},

    [0x60] = {name = "MOV",  args = {{register = "H"}, {register = "B"}}},
    [0x61] = {name = "MOV",  args = {{register = "H"}, {register = "C"}}},
    [0x62] = {name = "MOV",  args = {{register = "H"}, {register = "D"}}},
    [0x63] = {name = "MOV",  args = {{register = "H"}, {register = "E"}}},
    [0x64] = {name = "MOV",  args = {{register = "H"}, {register = "H"}}},
    [0x65] = {name = "MOV",  args = {{register = "H"}, {register = "L"}}},
    [0x66] = {name = "MOV",  args = {{register = "H"}, {register = "M"}}},
    [0x67] = {name = "MOV",  args = {{register = "H"}, {register = "A"}}},
    [0x68] = {name = "MOV",  args = {{register = "L"}, {register = "B"}}},
    [0x69] = {name = "MOV",  args = {{register = "L"}, {register = "C"}}},
    [0x6a] = {name = "MOV",  args = {{register = "L"}, {register = "D"}}},
    [0x6b] = {name = "MOV",  args = {{register = "L"}, {register = "E"}}},
    [0x6c] = {name = "MOV",  args = {{register = "L"}, {register = "H"}}},
    [0x6d] = {name = "MOV",  args = {{register = "L"}, {register = "L"}}},
    [0x6e] = {name = "MOV",  args = {{register = "L"}, {register = "M"}}},
    [0x6f] = {name = "MOV",  args = {{register = "L"}, {register = "A"}}},

    [0x70] = {name = "MOV",  args = {{register = "M"}, {register = "B"}}},
    [0x71] = {name = "MOV",  args = {{register = "M"}, {register = "C"}}},
    [0x72] = {name = "MOV",  args = {{register = "M"}, {register = "D"}}},
    [0x73] = {name = "MOV",  args = {{register = "M"}, {register = "E"}}},
    [0x74] = {name = "MOV",  args = {{register = "M"}, {register = "H"}}},
    [0x75] = {name = "MOV",  args = {{register = "M"}, {register = "L"}}},
    [0x76] = {name = "HLT",  args = {}},
    [0x77] = {name = "MOV",  args = {{register = "M"}, {register = "A"}}},
    [0x78] = {name = "MOV",  args = {{register = "A"}, {register = "B"}}},
    [0x79] = {name = "MOV",  args = {{register = "A"}, {register = "C"}}},
    [0x7a] = {name = "MOV",  args = {{register = "A"}, {register = "D"}}},
    [0x7b] = {name = "MOV",  args = {{register = "A"}, {register = "E"}}},
    [0x7c] = {name = "MOV",  args = {{register = "A"}, {register = "H"}}},
    [0x7d] = {name = "MOV",  args = {{register = "A"}, {register = "L"}}},
    [0x7e] = {name = "MOV",  args = {{register = "A"}, {register = "M"}}},
    [0x7f] = {name = "MOV",  args = {{register = "A"}, {register = "A"}}},

    [0x80] = {name = "ADD",  args = {{register = "B"}}},
    [0x81] = {name = "ADD",  args = {{register = "C"}}},
    [0x82] = {name = "ADD",  args = {{register = "D"}}},
    [0x83] = {name = "ADD",  args = {{register = "E"}}},
    [0x84] = {name = "ADD",  args = {{register = "H"}}},
    [0x85] = {name = "ADD",  args = {{register = "L"}}},
    [0x86] = {name = "ADD",  args = {{register = "M"}}},
    [0x87] = {name = "ADD",  args = {{register = "A"}}},
    [0x88] = {name = "ADC",  args = {{register = "B"}}},
    [0x89] = {name = "ADC",  args = {{register = "C"}}},
    [0x8a] = {name = "ADC",  args = {{register = "D"}}},
    [0x8b] = {name = "ADC",  args = {{register = "E"}}},
    [0x8c] = {name = "ADC",  args = {{register = "H"}}},
    [0x8d] = {name = "ADC",  args = {{register = "L"}}},
    [0x8e] = {name = "ADC",  args = {{register = "M"}}},
    [0x8f] = {name = "ADC",  args = {{register = "A"}}},

    [0x90] = {name = "SUB",  args = {{register = "B"}}},
    [0x91] = {name = "SUB",  args = {{register = "C"}}},
    [0x92] = {name = "SUB",  args = {{register = "D"}}},
    [0x93] = {name = "SUB",  args = {{register = "E"}}},
    [0x94] = {name = "SUB",  args = {{register = "H"}}},
    [0x95] = {name = "SUB",  args = {{register = "L"}}},
    [0x96] = {name = "SUB",  args = {{register = "M"}}},
    [0x97] = {name = "SUB",  args = {{register = "A"}}},
    [0x98] = {name = "SBB",  args = {{register = "B"}}},
    [0x99] = {name = "SBB",  args = {{register = "C"}}},
    [0x9a] = {name = "SBB",  args = {{register = "D"}}},
    [0x9b] = {name = "SBB",  args = {{register = "E"}}},
    [0x9c] = {name = "SBB",  args = {{register = "H"}}},
    [0x9d] = {name = "SBB",  args = {{register = "L"}}},
    [0x9e] = {name = "SBB",  args = {{register = "M"}}},
    [0x9f] = {name = "SBB",  args = {{register = "A"}}},

    [0xa0] = {name = "ANA",  args = {{register = "B"}}},
    [0xa1] = {name = "ANA",  args = {{register = "C"}}},
    [0xa2] = {name = "ANA",  args = {{register = "D"}}},
    [0xa3] = {name = "ANA",  args = {{register = "E"}}},
    [0xa4] = {name = "ANA",  args = {{register = "H"}}},
    [0xa5] = {name = "ANA",  args = {{register = "L"}}},
    [0xa6] = {name = "ANA",  args = {{register = "M"}}},
    [0xa7] = {name = "ANA",  args = {{register = "A"}}},
    [0xa8] = {name = "XRA",  args = {{register = "B"}}},
    [0xa9] = {name = "XRA",  args = {{register = "C"}}},
    [0xaa] = {name = "XRA",  args = {{register = "D"}}},
    [0xab] = {name = "XRA",  args = {{register = "E"}}},
    [0xac] = {name = "XRA",  args = {{register = "H"}}},
    [0xad] = {name = "XRA",  args = {{register = "L"}}},
    [0xae] = {name = "XRA",  args = {{register = "M"}}},
    [0xaf] = {name = "XRA",  args = {{register = "A"}}},

    [0xb0] = {name = "ORA",  args = {{register = "B"}}},
    [0xb1] = {name = "ORA",  args = {{register = "C"}}},
    [0xb2] = {name = "ORA",  args = {{register = "D"}}},
    [0xb3] = {name = "ORA",  args = {{register = "E"}}},
    [0xb4] = {name = "ORA",  args = {{register = "H"}}},
    [0xb5] = {name = "ORA",  args = {{register = "L"}}},
    [0xb6] = {name = "ORA",  args = {{register = "M"}}},
    [0xb7] = {name = "ORA",  args = {{register = "A"}}},
    [0xb8] = {name = "CMP",  args = {{register = "B"}}},
    [0xb9] = {name = "CMP",  args = {{register = "C"}}},
    [0xba] = {name = "CMP",  args = {{register = "D"}}},
    [0xbb] = {name = "CMP",  args = {{register = "E"}}},
    [0xbc] = {name = "CMP",  args = {{register = "H"}}},
    [0xbd] = {name = "CMP",  args = {{register = "L"}}},
    [0xbe] = {name = "CMP",  args = {{register = "M"}}},
    [0xbf] = {name = "CMP",  args = {{register = "A"}}},

    [0xc0] = {name = "RNZ",  args = {}},
    [0xc1] = {name = "POP",  args = {{register_pair = "B"}}},
    [0xc2] = {name = "JNZ",  args = {{word = "address"}}},
    [0xc3] = {name = "JMP",  args = {{word = "address"}}},
    [0xc4] = {name = "CNZ",  args = {{word = "address"}}},
    [0xc5] = {name = "PUSH", args = {{register_pair = "B"}}},
    [0xc6] = {name = "ADI",  args = {{byte = "data"}}},
    [0xc7] = {name = "RST",  args = {{faux = 0}}},
    [0xc8] = {name = "RZ",   args = {}},
    [0xc9] = {name = "RET",  args = {}},
    [0xca] = {name = "JZ",   args = {{word = "address"}}},
    [0xcc] = {name = "CZ",   args = {{word = "address"}}},
    [0xcd] = {name = "CALL", args = {{word = "address"}}},
    [0xce] = {name = "ACI",  args = {{byte = "data"}}},
    [0xcf] = {name = "RST",  args = {{faux = 1}}},
}
